// document.write("Simple interest Calculator");
// let p = prompt("Enter the principle amount:");
// let r = prompt("Enter the rate of interest:");
// let t = prompt("Enter the time duration:");
// p = parseFloat(p);
// r = parseFloat(r);
// t = parseFloat(t);
// document.write("The Simple Interest of " + p + "+" + r + "+" + t + " =");
// document.write((p * r * t) / 100);
// document.write("The total amount is " + (p + (p * r * t) / 100));

document.writeln("Math.log10(100) = ");
document.writeln(Math.log10(100));
document.writeln("<br>");
document.writeln(Math.pow(2, 3));
document.writeln("<br>");
document.writeln(Math.sqrt(16));
document.writeln("<br>");
document.writeln(Math.round(4.7));
document.writeln("<br>");
document.writeln(Math.ceil(4.2));
document.writeln("<br>");
document.writeln(Math.floor(4.7));
document.writeln("<br>");
document.writeln(Math.random());
document.writeln("<br>");
document.writeln(Math.abs(-5));
document.writeln("<br>");
document.writeln(Math.max(1, 2, 3, 4, 5));
document.writeln("<br>");
document.writeln(Math.min(1, 2, 3, 4, 5));
document.writeln("<br>");
document.writeln(Math.pow(2, 3));
document.writeln("<br>");
console.log(Math.random());
